Guide/cms/models.py
import datetime

from exts import db,bcrypt
from flask_login import AnonymousUserMixin


# role与user 多对多关系表

roles = db.Table(
    'role_users',
    db.Column('user_id', db.Integer, db.ForeignKey('admin_user.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('admin_role.id')),
)


# 创建第一个模型
# Flask Admin 用户
class User(db.Model):
    # 默认 表名 是类名小写版本；使用这个函数，指定表名
    __tablename__ = 'admin_user'
    # 每个 模型 必须有主键
    id = db.Column(db.Integer(), primary_key=True, autoincrement=True)
    email = db.Column(db.String(50), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)
    enabled = db.Column(db.Boolean(), default=0)  # 是否激活,暂时设置为自动激活
    realname = db.Column(db.String(30))  # 真实姓名

    create_time = db.Column(db.DateTime, default=datetime.datetime.now)

    # 与roles的多对多外键
    roles = db.relationship(
        'Role',
        secondary=roles,
        backref=db.backref('users', lazy='dynamic')
    )

    def __init__(self):
        default = Role.query.filter_by(name="default").one()
        self.roles.append(default)


    def __repr__(self):
        return "<User '{}'>".format(self.email)

    def set_password(self, password):
        """ 设置 password 加密 """
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, password):
        """ 把 传入的password加密，并与成员 password比较 """
        return bcrypt.check_password_hash(self.password, password)

    def is_authenticated(self):
        """ Flask_Login 需要：表示User对象是否已登录
            Flask Login中，网站上每个用户都是从某些基础的用户对象继承而来，默认他们继承 AnonymousUserMixin 对象
        """
        if isinstance(self, AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        """ Flask_Login 需要：是否通过了某种激活流程 """
        return self.enabled
        # return True

    def is_anonymous(self):
        """ Flask_Login 需要：访问者是否处于未登录的匿名状态 """
        if isinstance(self, AnonymousUserMixin):
            return True
        else:
            return False

    def get_id(self):
        """ Flask_Login 需要：返回User对象的唯一识别标志，即一个unicode字符串 """
        return str(self.id)  # python 2: return unicode(self.id)


# Flask Principal 角色
class Role(db.Model):
    __tablename__ = 'admin_role'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Role {}'.format(self.name)

Guide/cms/__init__.py
from .views import cms_bluePrint

Guide/cms/views.py
from flask import Blueprint, render_template, redirect, url_for, session, g, flash, request, jsonify, current_app
from flask_login import login_required, logout_user, login_user, current_user
from flask_principal import identity_changed, Identity
import logging
import config

from cms.form import LoginForm, RegisterForm, ChangePassForm
from cms.models import User
from cms.tools import Check_Url
from common.models import Classify, WebSite
from exts import db, admin_permission

cms_bluePrint = Blueprint('cms',__name__,static_folder='templates/cms',url_prefix='/cms')


@cms_bluePrint.before_request
def before_request():
    if current_user.is_authenticated:
        if admin_permission.can():
            g.is_admin = True
        else:
            g.is_admin = False
        g.user = current_user
    else:
        g.user = None


@cms_bluePrint.route('/login/', methods=['GET','POST'])
def login():
    logging.info('CMS用户‘{}’进行了登录操作'.format(current_user.email))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user, remember=form.remember.data)

        # flask_principal 登录后，触发 on_identity_loaded 方法，创建Need 对象
        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.id)
        )
        # session['email'] = user.email
        return redirect(url_for('cms.index'))

    return render_template('cms/login.html',form=form)


@cms_bluePrint.route('/logout/', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('cms.login'))


@cms_bluePrint.route('/regist/', methods=['GET','POST'])
def regist():
    logging.info('CMS用户注册')
    form = RegisterForm()
    if form.validate_on_submit():
        user = User()
        user.email = form.email.data
        user.realname = form.realname.data
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('cms.login'))
    return render_template('cms/regist.html',form=form)


@cms_bluePrint.route('/changepass', methods=['GET', 'POST'])
def changepass():
    """ 修改密码 """
    logging.info('修改密码')
    form = ChangePassForm()
    if form.validate_on_submit():
        new_user = User.query.filter_by(email=form.email.data).first()
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()

        flash("密码已成功修改， 请重新登陆。", category="success")
        return redirect(url_for('cms.login'))
    return render_template('cms/changepass.html', form=form)


@cms_bluePrint.route('/index/', methods=['GET'])
@login_required
def index():
    logging.info('进入CMS管理主页')
    form = {}
    classifys = db.session.query(Classify).order_by(Classify.weight.desc()).order_by(Classify.create_time.desc()).all()
    webs = db.session.query(WebSite).order_by(WebSite.create_time.desc())
    category = request.args.get('category')
    pageno = request.args.get('pageno')
    status = request.args.get('status')
    website_name = request.args.get('website_name')
    form['category'] = category
    form['status'] = status
    form['website_name'] = website_name
    if category:
        webs = webs.filter(WebSite.website_classify_id == category)
    if status:
        webs = webs.filter(WebSite.website_status == int(status))
    if website_name:
        webs = webs.filter(WebSite.website_name.ilike('%'+website_name+'%'))

    page = 1
    count = webs.count()
    if pageno:
        page = int(pageno)

    webs = webs.paginate(page=page, per_page=config.PAGE_LIMIT)

    content = {
        'classifys' : classifys,
        'webs': webs,
        'form':form,
        'count' : count,
        'limit': config.PAGE_LIMIT,
        'curr' : page
    }
    return render_template('cms/index.html', **content)


@cms_bluePrint.route('/AddWebInfo/', methods=['POST'])
@login_required
def AddWebInfo():

    category1 = request.form.get('category1')
    web_name = request.form.get('web_name')
    web_url = request.form.get('web_url')
    web_intro = request.form.get('web_intro')
    logging.info('添加了《{}》的网站信息'.format(web_name))
    web = WebSite(website_name=web_name, website_url=web_url, website_intro=web_intro, website_status=0, website_classify_id=int(category1))
    db.session.add(web)
    db.session.commit()
    return redirect(url_for('cms.index'))


@cms_bluePrint.route('/Upline/', methods=['POST'])
@login_required
def Upline():
    logging.info('进入了网站上线的操作！')
    web_id = request.form.get('web_id')
    web = WebSite.query.filter(WebSite.id == web_id).first()
    if web and web.website_status == 0:
        web.website_status = 1
        db.session.commit()
        logging.info('进行了《{}》网站的上线操作！'.format(web.website_name))
        return jsonify({'code':200,'msg':'上线成功！'})
    else:
        return jsonify({'code':404,'msg':'上线失败'})


@cms_bluePrint.route('/Downline/', methods=['POST'])
@login_required
def Downline():
    logging.info('进入了网站下线的视图函数！')
    web_id = request.form.get('web_id')
    web = WebSite.query.filter(WebSite.id == web_id).first()
    if web and web.website_status == 1:
        web.website_status = 0
        db.session.commit()
        logging.info('进行了《{}》网站的下线操作！'.format(web.website_name))
        return jsonify({'code':200,'msg':'下线成功！'})
    else:
        return jsonify({'code':404,'msg':'下线失败'})


@cms_bluePrint.route('/UpdateWeb/', methods=['POST'])
@login_required
def UpdateWeb():
    logging.info('进入了网站信息修改的视图函数！')
    web_id = request.form.get('web_id')
    category2 = request.form.get('category2')
    web_name = request.form.get('web_name')
    web_url = request.form.get('web_url')
    web_intro = request.form.get('web_intro')
    web = WebSite.query.filter(WebSite.id == web_id).first()
    if web:
        web.website_classify_id = category2
        web.website_name = web_name
        web.website_url = web_url
        web.website_intro = web_intro
        db.session.commit()
        logging.info('修改《》网站信息成功！'.format(web.website_name))
        flash('修改网站信息成功！')
        return redirect(url_for('cms.index'))
    else:
        flash('网站不存在！')
        return redirect(url_for('cms.index'))


@cms_bluePrint.route('/Delwebsite/', methods=['POST'])
@login_required
def Delwebsite():
    id = request.form.get('id')
    web = WebSite.query.filter(WebSite.id == id).first()
    if web:
        db.session.delete(web)
        db.session.commit()
        logging.info('删除《》网站信息成功！'.format(web.website_name))
        return jsonify({'code':200,'msg':'删除成功！'})
    else:
        return jsonify({'code':404,'msg':'删除失败！'})


@cms_bluePrint.route('/classify/')
@login_required
def classify():
    logging.info('进入了网站分类管理的视图函数！')
    classifys = Classify.query.order_by(Classify.weight.desc()).order_by(Classify.create_time.desc()).all()
    content = {
        'classifys': classifys
    }
    return render_template('cms/classify.html', **content)


@cms_bluePrint.route('/AddClassify/', methods=['POST'])
@login_required
def AddClassify():
    classify_name = request.form.get('classify_name')
    weight = request.form.get('weight')
    logging.info('添加了新的网站分类《%s》，权重为%s'%(classify_name, weight))
    classify = Classify.query.filter(Classify.classify_name == classify_name).first()
    if not classify:
        classify = Classify(classify_name=classify_name,weight=weight)
        db.session.add(classify)
        db.session.commit()

    return redirect(url_for('cms.classify'))


@cms_bluePrint.route('/changeClassify/', methods=['POST'])
@login_required
def changeClassify():
    c_id = request.form.get('c_id')
    weight = request.form.get('weight')
    classify_name = request.form.get('classify_name')
    classify = Classify.query.filter(Classify.id == c_id).first()
    if classify:
        classify.classify_name = classify_name
        classify.weight = weight
        db.session.commit()
        logging.info('修改了网站分类《%s》的信息，新权重为%s'%(classify_name, weight))

    return redirect(url_for('cms.classify'))


@cms_bluePrint.route('/check/', methods=['GET','POST'])
@login_required
def check():
    logging.info('进入了网址检测主页！')
    return render_template('cms/check.html')


@cms_bluePrint.route('/check_url/', methods=['POST'])
@login_required
def check_url():
    webs = WebSite.query.filter(WebSite.website_status == 1).all()
    count = len(webs)
    m = 0
    for web in webs:
        if not Check_Url(web.website_url):
            m+=1
            web.website_status = 0
            db.session.commit()
    logging.info('网址检测结果：共检测%s个正在上线的网址,无效的有%s个,已进行下线处理！'%(count,m))
    return jsonify({'code':200,'msg':'共%s个上线网址,无效的有%s个,已进行下线处理！'%(count,m)})


@cms_bluePrint.route('/account/')
@login_required
def account():
    logging.info('进入CMS用户管理主页')
    users = User.query.all()
    content = {
        'users': users
    }
    return render_template('cms/account.html', **content)


@cms_bluePrint.route('/account/do_act/<int:id>')
@login_required
def do_act(id):
    """
    激活用户账号的视图函数
    :return:
    """
    user = User.query.filter_by(id=id).first()
    user.enabled = 1
    logging.info('CMS用户《{}》进行了激活'.format(user.realname))
    db.session.commit()
    return redirect(url_for('cms.account'))


@cms_bluePrint.route('/account/undo_act/<int:id>')
def undo_act(id):
    """
    封停用户账号的视图函数
    :return:
    """
    user = User.query.filter_by(id=id).first()
    user.enabled = 0
    db.session.commit()
    logging.info('CMS用户《{}》进行了封禁'.format(user.realname))
    return redirect(url_for('cms.account'))

Guide/templates/cms/account.html
{% extends 'cms/index_base.html' %}

{% block head -%}

{%- endblock %}

{% block title -%}
    CMS账号管理
{%- endblock %}

{% block main -%}
    <h2>账号管理</h2>
    <hr>
    <div>
        <table class="layui-table">
          <colgroup>
              <col>
          </colgroup>
            <thead>
            <tr>
                <th>序号</th>
                <th>id</th>
                <th>用户邮箱</th>
                <th>姓名</th>
                <th>注册时间</th>
                <th>当前状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ user.id }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.realname }}</td>
                    <td>{{ user.create_time }}</td>
                    <td>
                    {% if user.enabled %}
                        <span class="layui-badge layui-bg-green">正常</span>
                    {% else %}
                        <span class="layui-badge layui-bg-red">未审核</span>
                    {% endif %}
                    </td>
                    <td>
                    {% if g.is_admin %}
                        {% if user.enabled %}
                            {% if user.email == g.user.email %}
                                <button class="layui-btn layui-btn-sm layui-btn-disabled">封禁</button>
                            {% else %}
                                <a class="layui-btn layui-btn-sm layui-bg-red" href="{{ url_for('cms.undo_act', id=user.id) }}">封禁</a>
                            {% endif %}
                        {% else %}
                            <a class="layui-btn layui-btn-sm"  href="{{ url_for('cms.do_act', id=user.id) }}">解封</a>
                        {% endif %}
                    {% else %}
                        权限不足
                    {% endif %}
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{%- endblock %}

{% block lay_js -%}

<script>
    layui.use(['layer','element','form','laypage'], function() {
        var form = layui.form
            ,layer = layui.layer
            ,element = layui.element
            ,laypage = layui.laypage
            , $ = layui.$;


        form.render();

        form.on('submit(*)', function(data){
          //console.log(data.field); //当前容器的全部表单字段，名值对形式：{name: value}

            //return false;
        });





        // 添加的模态框
        $('button.AddClassify').click(function () {
            layer.open({
                type: 1,
                shade: 0,
                title: '修改信息',
                skin: 'layui-layer-rim', //加上边框
                area: ['400px', '250px'], //宽高
                content: $('#AddClassifyBox')
            });
        });

        // 修改分类名称的模态框
        $('button.changename').click(function () {
            var self = $(this);
            var tr = self.parent().parent();
            var c_id = tr.attr('data-id');
            var name = tr.attr('data-name');
            var weight = tr.attr('data-weight');
            console.log(name);
            $('#c_id').val(c_id);
            $('#classify_name').val(name);
            $('#weight').val(weight);
            layer.open({
                type: 1,
                shade: 0,
                title: '修改信息',
                skin: 'layui-layer-rim', //加上边框
                area: ['400px', '250px'], //宽高
                content: $('#changeClassifyBox')
            });
        });


    });
</script>
{%- endblock %}

Guide/templates/cms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'common/_heads.html' %}
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body  class="layui-layout-body">
    {% block body -%}

    {%- endblock %}
</body>
</html>

Guide/templates/cms/changePass.html
{% extends 'cms/base.html' %}

{% block head %}

{% endblock %}

{% block title %}
注册页面
{% endblock %}

{% block body %}
{% if form.errors %}
    {% for field_name, field_errors in form.errors|dictsort if field_errors %}
        {% for error in field_errors %}
            <div class="alert alert-warning" role="alert">
                <p align="center" style="color:red;">{{ error }}</p>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
<div class="login" style="width:350px;margin: 0 auto;margin-top: 50px;">
        <h2>修改密码</h2>
        <hr>
        <form class="layui-form" action="{{ url_for('cms.changepass') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="layui-form-item">
                <label class="layui-form-label">邮箱</label>
                <div class="layui-input-block">
                <input type="email" name="email" required  lay-verify="email" placeholder="请输入邮箱" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">旧密码</label>
                <div class="layui-input-block">
                <input type="password" name="old_password" required lay-verify="old_pwd" placeholder="请输入原密码" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">新密码</label>
                <div class="layui-input-block">
                <input type="password" name="password" required lay-verify="pwd" placeholder="请输入新密码" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">重复密码</label>
                <div class="layui-input-block">
                <input type="password" name="repassword" required lay-verify="repwd" placeholder="请再次输入新密码" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                <button class="layui-btn" lay-submit lay-filter="formDemo">修改密码</button>
                <a  href="{{ url_for('cms.login') }}" class="layui-btn layui-btn-primary">返回登录</a>
                </div>
            </div>
        </form>
    </div>


    <script>
    //Demo
    layui.use(['layer','form'], function(){
        var form = layui.form
        ,$ = layui.$;

        //监听提交,false不提交，true为提交
        form.on('submit(formDemo)', function(data){
            {#layer.msg(JSON.stringify(data.field));#}
            return true;
        });

        form.verify({
            email: [/^[a-z0-9._%-]+@([a-z0-9-]+\.)+[a-z]{2,4}$|^1[3|4|5|7|8]\d{9}$/, '邮箱格式不对'],
            pwd: [/(.+){6,12}$/, '密码必须6到12位'],
            repwd: function(value){
                var data = $('input[name="password"]').val();
                if (data != value){
                    return '两次密码不一样'
                }
            }
        });
        form.render();
    });
    </script>
{% endblock %}

Guide/templates/cms/check.html
{% extends 'cms/index_base.html' %}

{% block head -%}

{%- endblock %}

{% block title -%}
    CMS网址检测
{%- endblock %}

{% block main -%}
    <h2>网址检测</h2>
    <h3>检测依据：是否可以正常访问，无法正常访问的网址都会直接下线</h3>
    <div>
        <button class="layui-btn layui-btn-sm Check_Url" style="margin: 10px;">检测全部网址</button>
    </div>
    <hr>
    <div>
        <table class="layui-table">
          <colgroup>
              <col>
              <col>
              <col>
              <col width="200">
              <col width="400">
            <col>
          </colgroup>
            <thead>
            <tr>
                <th>序号</th>
                <th>分类名称</th>
                <th>下属网站个数</th>
                <th>记录时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>


{%- endblock %}

{% block lay_js -%}

<script>
    layui.use(['layer','element','form','laypage'], function() {
        var form = layui.form
            ,layer = layui.layer
            ,element = layui.element
            ,laypage = layui.laypage
            , $ = layui.$;


        form.render();

        form.on('submit(*)', function(data){
          //console.log(data.field); //当前容器的全部表单字段，名值对形式：{name: value}

            return false;
        });

        // 检测网址的ajax请求
        $('button.Check_Url').click(function () {

            var layload = layer.msg('正在检测,请稍后...', {
                icon: 16
                , shade: 0.01
            });
            zlajax.post({
                'url': "{{ url_for('cms.check_url') }}",
                'success': function (data) {
                    if (data['code'] == 200) {
                        layer.close(layload);
                        layer.msg(data['msg'], {icon: 1, time: 3000});
                        setTimeout(function () {
                            parent.layer.closeAll();
                            location.reload();
                        }, 2000);
                    } else {
                        layer.close(layload);
                        setTimeout(function () {
                            parent.layer.closeAll();
                            location.reload();
                        }, 2000);
                        layer.msg(data['msg'], {icon: 5, time: 3000});
                    }
                },
                'error': function () {
                    layer.close(layload);
                    layer.msg("网络出现错误！", {icon: 2, time: 2000});
                }
            });
        });


    });
</script>
{%- endblock %}

Guide/templates/cms/classify.html
{% extends 'cms/index_base.html' %}

{% block head -%}

{%- endblock %}

{% block title -%}
    CMS类别管理
{%- endblock %}

{% block main -%}
    <h2>类别管理</h2>
    <div>
        <button class="layui-btn layui-btn-sm AddClassify" style="float: right;">添加类别</button>
    </div>
    <hr>
    <div>
        <table class="layui-table">
          <colgroup>
              <col>
              <col>
              <col>
              <col width="200">
              <col width="400">
            <col>
          </colgroup>
            <thead>
            <tr>
                <th>序号</th>
                <th>id</th>
                <th>分类名称</th>
                <th>下属网站个数</th>
                <th>排序权重</th>
                <th>记录时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for classify in classifys %}
                <tr data-id="{{ classify.id }}" data-name="{{ classify.classify_name }}" data-weight="{{ classify.weight }}">
                    <td>{{ loop.index }}</td>
                    <td>{{ classify.id }}</td>
                    <td>{{ classify.classify_name }}</td>
                    <td>{{ classify.webs|length }}</td>
                    <td>{{ classify.weight }}</td>
                    <td>{{ classify.create_time }}</td>
                    <td>
                        <button class="layui-btn layui-btn-sm changename">修改</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="pageNav"></div>



    <!--添加分类信息的模态框-->
    <div id="AddClassifyBox" style="display: none; width: 350px; margin-top: 10px;">
        <form class="layui-form" action="{{ url_for('cms.AddClassify') }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input type="hidden" name="web_id" id="web_id">
            <div class="layui-form-item">
                <label class="layui-form-label">分类名称</label>
                <div class="layui-input-block">
                    <input type="text" name="classify_name" autocomplete="off"
                           class="layui-input" lay-verify="required">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">排序权重</label>
                <div class="layui-input-block">
                    <input type="text" name="weight" autocomplete="off"
                           class="layui-input" lay-verify="required">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit lay-filter="*">立即提交</button>
                    <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
            </div>
        </form>
    </div>

    <!--修改分类信息的模态框-->
    <div id="changeClassifyBox" style="display: none; width: 350px; margin-top: 10px;">
        <form class="layui-form" action="{{ url_for('cms.changeClassify') }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input type="hidden" name="c_id" id="c_id">
            <div class="layui-form-item">
                <label class="layui-form-label">分类名称</label>
                <div class="layui-input-block">
                    <input type="text" name="classify_name" id="classify_name" autocomplete="off"
                           class="layui-input" lay-verify="required">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">排序权重</label>
                <div class="layui-input-block">
                    <input type="text" name="weight" id="weight" autocomplete="off"
                           class="layui-input" lay-verify="required">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit lay-filter="*">立即提交</button>
                    <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
            </div>
        </form>
    </div>
{%- endblock %}

{% block lay_js -%}

<script>
    layui.use(['layer','element','form','laypage'], function() {
        var form = layui.form
            ,layer = layui.layer
            ,element = layui.element
            ,laypage = layui.laypage
            , $ = layui.$;


        form.render();

        form.on('submit(*)', function(data){
          //console.log(data.field); //当前容器的全部表单字段，名值对形式：{name: value}

            //return false;
        });





        // 添加的模态框
        $('button.AddClassify').click(function () {
            layer.open({
                type: 1,
                shade: 0,
                title: '修改信息',
                skin: 'layui-layer-rim', //加上边框
                area: ['400px', '250px'], //宽高
                content: $('#AddClassifyBox')
            });
        });

        // 修改分类名称的模态框
        $('button.changename').click(function () {
            var self = $(this);
            var tr = self.parent().parent();
            var c_id = tr.attr('data-id');
            var name = tr.attr('data-name');
            var weight = tr.attr('data-weight');
            console.log(name);
            $('#c_id').val(c_id);
            $('#classify_name').val(name);
            $('#weight').val(weight);
            layer.open({
                type: 1,
                shade: 0,
                title: '修改信息',
                skin: 'layui-layer-rim', //加上边框
                area: ['400px', '250px'], //宽高
                content: $('#changeClassifyBox')
            });
        });


    });
</script>
{%- endblock %}

Guide/templates/cms/index_base.html
{% extends 'cms/base.html' %}

{% block head %}

{% endblock %}

{% block title %}

{% endblock %}


{% block body %}
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
    <a class="layui-logo" href="{{ url_for('cms.index') }}">编程网址导航后台</a>

      <ul class="layui-nav layui-layout-right">
          <li class="layui-nav-item">
          {% if g.user %}
              <a href="javascript:;">
                  <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
                  {{ g.user.realname }}
                </a>
        <dl class="layui-nav-child">
          <dd><a href="{{ url_for('cms.changepass') }}">修改密码</a></dd>
        </dl>
      </li>
              <li class="layui-nav-item"><a href="{{ url_for('cms.logout') }}">注销</a></li>
          {% else %}
              <li class="layui-nav-item"><a href="{{ url_for('cms.login') }}">登陆</a></li>
              <li class="layui-nav-item"><a href="{{ url_for('cms.regist') }}">注册</a></li>
          {% endif %}
      </ul>
  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree"  lay-filter="test">
        <li class="layui-nav-item layui-nav-itemed">
          <a class="" href="javascript:;">网址管理</a>
          <dl class="layui-nav-child">
              <dd><a href="{{ url_for('cms.index') }}">网址审核</a></dd>
              <dd><a href="{{ url_for('cms.classify') }}">类别管理</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item">
          <a href="javascript:;">爬虫管理</a>
          <dl class="layui-nav-child">
            <dd><a href="{{ url_for('cms.check') }}">检测</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item">
          <a href="javascript:;">CMS用户管理</a>
          <dl class="layui-nav-child">
            <dd><a href="{{ url_for('cms.account') }}">账号管理</a></dd>
          </dl>
        </li>
      </ul>
    </div>
  </div>

  <div class="layui-body">
    <!-- 内容主体区域 -->
    <div style="padding: 15px;">
    <!-- 表格区域 -->
        {% block main %}主体内容{% endblock %}
    </div>
  </div>

  <div class="layui-footer">
    <!-- 底部固定区域 -->
    @非专业IT导航-毕业设计
  </div>
</div>
    {% block lay_js %}lay_js脚本{% endblock %}
<script>
//JavaScript代码区域
layui.use('element', function(){
  var element = layui.element;

});
</script>
{% endblock %}