Guide/front/__init__.py
from .views import front_bluePrint

Guide/front/views.py
from flask import Blueprint, render_template, redirect, url_for, abort
from sqlalchemy import and_
from common.models import WebSite, Classify
from exts import db

front_bluePrint = Blueprint('front',__name__,static_folder='templates/front')


@front_bluePrint.route('/')
def index():

    classifys = Classify.query.order_by(Classify.weight.desc()).order_by(Classify.create_time.desc()).all()
    datas = {}
    for classify in classifys:
        webs = WebSite.query.filter(and_(WebSite.website_classify_id == classify.id, WebSite.website_status == 1)).limit(20).all()
        datas[classify] = webs
    content = {
        'datas' : datas
    }
    return render_template('front/index.html', **content)


@front_bluePrint.route('/detail/<int:c_id>')
def detail(c_id):
    classifys = Classify.query.filter(Classify.id == c_id).all()
    if not classifys:
        abort(404)
    datas = {}
    for classify in classifys:
        webs = WebSite.query.filter(
            and_(WebSite.website_classify_id == classify.id, WebSite.website_status == 1)).limit(20).all()
        datas[classify] = webs
    content = {
        'datas' : datas,
        'title' : classifys[0].classify_name
    }
    return render_template('front/index.html', **content)

Guide/templates/front/index.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ static('front/basic.css') }}">
    {% include 'common/_heads.html' %}
    <title>{{ title or '首页' }}-导航页</title>
</head>
<body>
    <div class="content">
        <div class="header">
            <div class="search">
                <h2 style="color: #ffffff;margin: 30px;">一个非专业的IT导航网站</h2>
                <form action="http://www.baidu.com/baidu" target="_blank">
                    <input name=tn type=hidden value=baidu>
                    <div>
                        <input type=text class="search_input" id="search_input" placeholder="输入搜索内容..." name=word>
                        <input type="submit" value="百度一下" title="百度一下" id="search_btn">
                    </div>
                </form>
            </div>
        </div>
        <div class="main">
            {% for classify,webs in datas.items() %}
                {% if webs|length > 0 %}
                <div class="content-list" id="list{{ classify.id }}">
                    <p class="content-list-title">
                        <span>{{ classify.classify_name }}</span>
                        <a class="more" href="{{ url_for('front.detail', c_id = classify.id) }}" target="_blank" title="更多">更多>></a>
                    </p>
                <div>
                    <ul class="content-list-text">
                        {% for web in webs %}
                            {% if web.website_status %}
                            <li>
                                <a href="{{ web.website_url }}#" target="_blank" rel="nofollow" title="{{ web.website_name }}">{{ web.website_name }}</a>
                                <p title="{{ web.website_intro }}">{{ web.website_intro|truncate(length=40) }}</p>
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="footer" style="width: 100%; height: 150px;float: left;margin-top: 10px;background:#ffffff;text-align: center;">
            <p style="width: 100%;height: 50px;">
            </p>
            作者联系方式：978326643@qq.com
            <br>	
            <strong><a href="http://www.beian.miit.gov.cn/" target="_blank">豫ICP备19022224号</a></strong>    
        </div>
        <div id="Popup">
            <ul>
                {% for classify,webs in datas.items() %}
                    {% if webs|length > 0 %}
                    <li><a href="#list{{ classify.id }}" title="{{ classify.classify_name }}">{{ classify.classify_name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</body>

</html>